name = "HighEnergyTools"
uuid = "149a2eba-cee4-405f-968b-14c210176bd1"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>", "Marian Stahl <marian.stahl@cern.ch>", "Ilya Segal <ilya.segal@@cern.ch>", "Dhruvanshu Parmar <dhruvanshu.mahesh.parmar@cern.ch>"]
version = "0.7.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
Distributions = "0.25.120"
QuadGK = "2"
julia = ">= 1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
